# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mosaic < Formula
  desc "TUI command center for running 10+ AI coding agents in parallel"
  homepage "https://github.com/Mizune/mosaic"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Mizune/mosaic/releases/download/v0.9.0/mosaic_0.9.0_darwin_amd64.tar.gz"
      sha256 "2e3396498c024809d238727bee3cccbb41a87c0e957ccf1f56e0a7cce687afac"

      define_method(:install) do
        bin.install "mosaic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Mizune/mosaic/releases/download/v0.9.0/mosaic_0.9.0_darwin_arm64.tar.gz"
      sha256 "652cc9214cb7bc96766182290ae5fb626bfe21cc2f95ceb3d7e990a640938697"

      define_method(:install) do
        bin.install "mosaic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Mizune/mosaic/releases/download/v0.9.0/mosaic_0.9.0_linux_amd64.tar.gz"
      sha256 "510c26190f2c0ecc3cc98d4f5413ee66e5acb0d402cee97f459cb382b11ec595"
      define_method(:install) do
        bin.install "mosaic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Mizune/mosaic/releases/download/v0.9.0/mosaic_0.9.0_linux_arm64.tar.gz"
      sha256 "70d9e4f5db667503cda508f23eed9f2e30313390764b5ddb2c26449b554bf86c"
      define_method(:install) do
        bin.install "mosaic"
      end
    end
  end

  def post_install
    system "xattr", "-cr", bin/"mosaic"
  end

  test do
    system "#{bin}/mosaic", "--version"
  end
end
