# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mosaic < Formula
  desc "TUI command center for running 10+ AI coding agents in parallel"
  homepage "https://github.com/Mizune/mosaic"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Mizune/mosaic/releases/download/v0.7.0/mosaic_0.7.0_darwin_amd64.tar.gz"
      sha256 "6b4d25d30b7cbe43f9fba726519ea8717edd167d00388690590dc4edf618b398"

      define_method(:install) do
        bin.install "mosaic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Mizune/mosaic/releases/download/v0.7.0/mosaic_0.7.0_darwin_arm64.tar.gz"
      sha256 "3909a4bbd669d9de05496c78690536daad0ed178a0fb09403dafff64d8ecd9dd"

      define_method(:install) do
        bin.install "mosaic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Mizune/mosaic/releases/download/v0.7.0/mosaic_0.7.0_linux_amd64.tar.gz"
      sha256 "fc5ff99ea6909da3f18f71a51048c61aa9b465f05a84085f41df6a3095a9b0b8"
      define_method(:install) do
        bin.install "mosaic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Mizune/mosaic/releases/download/v0.7.0/mosaic_0.7.0_linux_arm64.tar.gz"
      sha256 "59eae0f207a292861aa0d09f15c0986e00c9c6d12ff750bed54b44401d6b40ae"
      define_method(:install) do
        bin.install "mosaic"
      end
    end
  end

  def post_install
    system "xattr", "-cr", bin/"mosaic"
  end

  test do
    system "#{bin}/mosaic", "--version"
  end
end
